version: '3.4'

services:
  postgres:
    restart: always
    image: postgres:10.7
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: beautyathome/api:latest
    environment:
      - DB_TYPE=postgres
    depends_on:
      - postgres
    volumes:
      - ./build/libs:/app
    ports:
      - 8080:8080
    env_file:
      - local.env
    command: java -server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:InitialRAMFraction=2 -XX:MinRAMFraction=2 -XX:MaxRAMFraction=2 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -jar bath.jar

volumes:
  postgres_data: